/**
 * report-generator.ts
 * Generates a sustainability report PDF in the browser using jsPDF.
 * Called after a report row is created in the DB (status: "pending").
 * Returns the PDF as a Blob so we can:
 *   1. Trigger a browser download immediately
 *   2. Compute file_size_kb to store back in the DB
 */

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { supabase } from "@/lib/supabase";
import type {
  ReportTemplate,
  ReportKpiDefinition,
  KpiRiskIndicator,
  EnergyDailySummary,
  CarbonScopeReading,
  Investment,
  Subsidy,
} from "@/lib/types";

/* ─── colour palette (hex, no CSS vars — jsPDF doesn't resolve them) ─── */
const CLR = {
  primary: [30, 174, 152] as [number, number, number],   // teal-ish
  dark:    [15, 23, 42]   as [number, number, number],   // slate-900
  mid:     [51, 65, 85]   as [number, number, number],   // slate-700
  light:   [148, 163, 184] as [number, number, number],  // slate-400
  white:   [255, 255, 255] as [number, number, number],
  success: [34, 197, 94]  as [number, number, number],   // green-500
  warn:    [234, 179, 8]  as [number, number, number],   // yellow-500
  danger:  [239, 68, 68]  as [number, number, number],   // red-500
  accent:  [99, 102, 241] as [number, number, number],   // indigo-500
};

type RGB = [number, number, number];

/* ─── helpers ─── */
function setFill(doc: jsPDF, rgb: RGB) { doc.setFillColor(...rgb); }
function setDraw(doc: jsPDF, rgb: RGB) { doc.setDrawColor(...rgb); }
function setTextColor(doc: jsPDF, rgb: RGB) { doc.setTextColor(...rgb); }

function statusColor(status: string): RGB {
  if (status === "on-track" || status === "achieved") return CLR.success;
  if (status === "at-risk") return CLR.warn;
  if (status === "critical") return CLR.danger;
  return CLR.light;
}

/* ─── fetch helpers — each returns [] on error so PDF still renders ─── */
async function fetchKpiRisk(campusId: number): Promise<KpiRiskIndicator[]> {
  const { data } = await supabase
    .from("kpi_risk_indicators")
    .select("*")
    .eq("campus_id", campusId)
    .order("kpi_name");
  return (data ?? []) as KpiRiskIndicator[];
}

async function fetchEnergy(campusId: number): Promise<EnergyDailySummary[]> {
  const { data } = await supabase
    .from("energy_daily_summaries")
    .select("*")
    .eq("campus_id", campusId)
    .order("summary_date", { ascending: false })
    .limit(30);
  return (data ?? []) as EnergyDailySummary[];
}

async function fetchCarbon(campusId: number): Promise<CarbonScopeReading[]> {
  const { data } = await supabase
    .from("carbon_scope_readings")
    .select("*")
    .eq("campus_id", campusId)
    .order("recorded_month", { ascending: false })
    .limit(12);
  return (data ?? []) as CarbonScopeReading[];
}

async function fetchInvestments(campusId: number): Promise<Investment[]> {
  const { data } = await supabase
    .from("investments")
    .select("*")
    .eq("campus_id", campusId)
    .order("created_at", { ascending: false })
    .limit(20);
  return (data ?? []) as Investment[];
}

async function fetchSubsidies(campusId: number): Promise<Subsidy[]> {
  const { data } = await supabase
    .from("subsidies")
    .select("*")
    .eq("campus_id", campusId)
    .order("created_at", { ascending: false })
    .limit(20);
  return (data ?? []) as Subsidy[];
}

/* ─── section drawers ─── */

function drawCoverPage(
  doc: jsPDF,
  template: ReportTemplate,
  periodLabel: string,
  generatorName: string,
  W: number,
  H: number,
) {
  // dark background
  setFill(doc, CLR.dark);
  doc.rect(0, 0, W, H, "F");

  // accent stripe
  setFill(doc, CLR.primary);
  doc.rect(0, 0, 6, H, "F");

  // logo-ish text
  setTextColor(doc, CLR.primary);
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text("EcoVista", 20, 40);

  // template name
  setTextColor(doc, CLR.white);
  doc.setFontSize(22);
  doc.text(template.name, 20, 70, { maxWidth: W - 40 });

  // standard badge
  if (template.standard) {
    setFill(doc, CLR.primary);
    const badgeW = doc.getTextWidth(template.standard) + 10;
    doc.roundedRect(20, 80, badgeW, 10, 2, 2, "F");
    setTextColor(doc, CLR.white);
    doc.setFontSize(9);
    doc.text(template.standard, 25, 87);
  }

  // meta block
  const metaY = 110;
  setTextColor(doc, CLR.light);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Period: ${periodLabel}`, 20, metaY);
  doc.text(`Generated: ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}`, 20, metaY + 8);
  doc.text(`Generated by: ${generatorName}`, 20, metaY + 16);
  if (template.section_count) {
    doc.text(`Sections covered: ${template.section_count}`, 20, metaY + 24);
  }

  // divider
  setDraw(doc, CLR.mid);
  doc.setLineWidth(0.3);
  doc.line(20, metaY + 36, W - 20, metaY + 36);

  // disclaimer
  setTextColor(doc, CLR.light);
  doc.setFontSize(7.5);
  doc.text(
    "This report was auto-generated from live campus data. Verify figures before external submission.",
    20,
    metaY + 46,
    { maxWidth: W - 40 },
  );
}

function drawSectionHeader(doc: jsPDF, title: string, y: number, W: number): number {
  setFill(doc, CLR.mid);
  doc.rect(14, y, W - 28, 8, "F");
  setTextColor(doc, CLR.white);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(title, 18, y + 5.5);
  return y + 14;
}

function drawKpiSection(doc: jsPDF, kpis: KpiRiskIndicator[], startY: number, W: number): number {
  let y = drawSectionHeader(doc, "Sustainability KPI Risk Indicators", startY, W);
  if (kpis.length === 0) {
    setTextColor(doc, CLR.light);
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.text("No KPI data available for this campus.", 14, y + 4);
    return y + 14;
  }
  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    head: [["KPI", "Current", "Target", "Unit", "Status", "Deadline"]],
    body: kpis.map(k => [
      k.kpi_name,
      k.current_value.toLocaleString(),
      k.target_value.toLocaleString(),
      k.unit ?? "—",
      k.status,
      k.deadline_label ?? k.deadline_date ?? "—",
    ]),
    styles: { fontSize: 8, cellPadding: 2.5, textColor: [30, 41, 59] },
    headStyles: { fillColor: CLR.dark, textColor: CLR.white, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [241, 245, 249] },
    columnStyles: {
      4: {
        fontStyle: "bold",
        textColor: (data: { cell: { raw: unknown } }) => {
          const raw = String((data?.cell as { raw?: unknown })?.raw ?? "");
          return statusColor(raw);
        },
      },
    },
  });
  return (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
}

function drawEnergySection(doc: jsPDF, energy: EnergyDailySummary[], startY: number, W: number): number {
  let y = drawSectionHeader(doc, "Energy Consumption — Last 30 Days", startY, W);
  if (energy.length === 0) {
    setTextColor(doc, CLR.light);
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.text("No energy data available.", 14, y + 4);
    return y + 14;
  }

  // summary stats
  const totalKwh = energy.reduce((s, r) => s + (r.total_kwh ?? 0), 0);
  const solarKwh  = energy.reduce((s, r) => s + (r.solar_kwh  ?? 0), 0);
  const gridKwh   = energy.reduce((s, r) => s + (r.grid_kwh   ?? 0), 0);
  const totalCost = energy.reduce((s, r) => s + (r.cost_inr   ?? 0), 0);
  const renewPct  = totalKwh > 0 ? ((solarKwh / totalKwh) * 100).toFixed(1) : "0";

  const stats = [
    ["Total Consumption", `${(totalKwh / 1000).toFixed(1)} MWh`],
    ["Solar Generation", `${(solarKwh / 1000).toFixed(1)} MWh`],
    ["Grid Import", `${(gridKwh / 1000).toFixed(1)} MWh`],
    ["Renewable %", `${renewPct}%`],
    ["Total Cost", `₹${totalCost.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`],
  ];

  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    head: [["Metric", "Value"]],
    body: stats,
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    headStyles: { fillColor: CLR.accent, textColor: CLR.white, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [241, 245, 249] },
    columnStyles: { 1: { fontStyle: "bold" } },
    tableWidth: "auto",
  });
  y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;

  // last 10 days detailed
  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    head: [["Date", "Total kWh", "Solar kWh", "Grid kWh", "Carbon kg", "Cost ₹"]],
    body: energy.slice(0, 10).map(r => [
      r.summary_date,
      r.total_kwh?.toFixed(0) ?? "—",
      r.solar_kwh?.toFixed(0) ?? "—",
      r.grid_kwh?.toFixed(0) ?? "—",
      r.carbon_kg?.toFixed(1) ?? "—",
      r.cost_inr?.toLocaleString("en-IN", { maximumFractionDigits: 0 }) ?? "—",
    ]),
    styles: { fontSize: 7.5, cellPadding: 2 },
    headStyles: { fillColor: CLR.dark, textColor: CLR.white, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [241, 245, 249] },
  });
  return (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
}

function drawCarbonSection(doc: jsPDF, carbon: CarbonScopeReading[], startY: number, W: number): number {
  let y = drawSectionHeader(doc, "Carbon Emissions by Scope", startY, W);
  if (carbon.length === 0) {
    setTextColor(doc, CLR.light);
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.text("No carbon data available.", 14, y + 4);
    return y + 14;
  }

  // group by scope
  const byScope: Record<number, number> = {};
  carbon.forEach(c => { byScope[c.scope] = (byScope[c.scope] ?? 0) + c.value_tco2e; });

  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    head: [["Scope", "Description", "tCO₂e"]],
    body: [
      ["Scope 1", "Direct emissions (fuel, fleet)", byScope[1]?.toFixed(2) ?? "0.00"],
      ["Scope 2", "Purchased electricity & heat", byScope[2]?.toFixed(2) ?? "0.00"],
      ["Scope 3", "Value chain & travel", byScope[3]?.toFixed(2) ?? "0.00"],
    ],
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    headStyles: { fillColor: [22, 163, 74], textColor: CLR.white, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [241, 245, 249] },
    columnStyles: { 2: { fontStyle: "bold" } },
  });
  y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;

  // top sources table
  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    head: [["Month", "Source", "Scope", "tCO₂e", "Trend"]],
    body: carbon.slice(0, 12).map(c => [
      c.recorded_month,
      c.source_name,
      `Scope ${c.scope}`,
      c.value_tco2e.toFixed(2),
      c.trend_pct != null ? `${c.trend_pct > 0 ? "+" : ""}${c.trend_pct.toFixed(1)}%` : "—",
    ]),
    styles: { fontSize: 7.5, cellPadding: 2 },
    headStyles: { fillColor: CLR.dark, textColor: CLR.white, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [241, 245, 249] },
  });
  return (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
}

function drawFinanceSection(
  doc: jsPDF,
  investments: Investment[],
  subsidies: Subsidy[],
  startY: number,
  W: number,
): number {
  let y = drawSectionHeader(doc, "Finance & Investments", startY, W);

  if (investments.length > 0) {
    setTextColor(doc, CLR.mid);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("Investment Portfolio", 14, y);
    y += 4;

    autoTable(doc, {
      startY: y,
      margin: { left: 14, right: 14 },
      head: [["Investment", "Cost (Cr ₹)", "ROI %", "Impact Score", "Status"]],
      body: investments.map(i => [
        i.name,
        i.cost_cr?.toFixed(2) ?? "—",
        i.roi_pct?.toFixed(1) ?? "—",
        i.impact_score?.toFixed(0) ?? "—",
        i.status,
      ]),
      styles: { fontSize: 7.5, cellPadding: 2 },
      headStyles: { fillColor: CLR.accent, textColor: CLR.white, fontStyle: "bold" },
      alternateRowStyles: { fillColor: [241, 245, 249] },
    });
    y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;
  }

  if (subsidies.length > 0) {
    setTextColor(doc, CLR.mid);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("Subsidies & Grants", 14, y);
    y += 4;

    autoTable(doc, {
      startY: y,
      margin: { left: 14, right: 14 },
      head: [["Subsidy", "Amount (₹)", "Status", "Deadline"]],
      body: subsidies.map(s => [
        s.name,
        s.amount_inr.toLocaleString("en-IN"),
        s.status,
        s.deadline_text ?? s.deadline ?? "—",
      ]),
      styles: { fontSize: 7.5, cellPadding: 2 },
      headStyles: { fillColor: [22, 163, 74], textColor: CLR.white, fontStyle: "bold" },
      alternateRowStyles: { fillColor: [241, 245, 249] },
    });
    y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
  }

  if (investments.length === 0 && subsidies.length === 0) {
    setTextColor(doc, CLR.light);
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.text("No financial data available for this campus.", 14, y + 4);
    y += 14;
  }

  return y;
}

function drawSelectedKPIs(
  doc: jsPDF,
  allKpis: ReportKpiDefinition[],
  selectedIds: number[],
  startY: number,
  W: number,
): number {
  const chosen = selectedIds.length > 0
    ? allKpis.filter(k => selectedIds.includes(k.id))
    : allKpis;
  if (chosen.length === 0) return startY;

  let y = drawSectionHeader(doc, "Included KPI Definitions", startY, W);
  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    head: [["KPI Name", "Category", "Unit", "Period"]],
    body: chosen.map(k => [k.name, k.category ?? "—", k.unit ?? "—", k.period_label ?? "—"]),
    styles: { fontSize: 7.5, cellPadding: 2 },
    headStyles: { fillColor: CLR.mid, textColor: CLR.white, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [241, 245, 249] },
  });
  return (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
}

function drawFooter(doc: jsPDF, pageNum: number, totalPages: number, W: number, H: number) {
  setDraw(doc, CLR.mid);
  doc.setLineWidth(0.2);
  doc.line(14, H - 12, W - 14, H - 12);
  setTextColor(doc, CLR.light);
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.text("EcoVista — Sustainability Intelligence Platform", 14, H - 7);
  doc.text(`Page ${pageNum} of ${totalPages}`, W - 14, H - 7, { align: "right" });
}

/* ─── main export ─── */
export interface GeneratePdfOptions {
  campusId: number;
  template: ReportTemplate;
  periodLabel: string;
  selectedKpiIds: number[];
  allKpiDefinitions: ReportKpiDefinition[];
  generatorName: string;
}

export async function generateReportPdf(opts: GeneratePdfOptions): Promise<Blob> {
  const { campusId, template, periodLabel, selectedKpiIds, allKpiDefinitions, generatorName } = opts;

  // fetch live data in parallel
  const [kpiRisk, energy, carbon, investments, subsidies] = await Promise.all([
    fetchKpiRisk(campusId),
    fetchEnergy(campusId),
    fetchCarbon(campusId),
    fetchInvestments(campusId),
    fetchSubsidies(campusId),
  ]);

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();

  /* ── Page 1: cover ── */
  drawCoverPage(doc, template, periodLabel, generatorName, W, H);

  /* ── Page 2+: data sections ── */
  doc.addPage();
  let y = 20;

  const checkPageBreak = (needed: number) => {
    if (y + needed > H - 20) {
      doc.addPage();
      y = 20;
    }
  };

  // 1. KPI Risk Indicators
  checkPageBreak(40);
  y = drawKpiSection(doc, kpiRisk, y, W);

  // 2. Energy
  checkPageBreak(40);
  y = drawEnergySection(doc, energy, y, W);

  // 3. Carbon
  checkPageBreak(40);
  y = drawCarbonSection(doc, carbon, y, W);

  // 4. Finance (only if template is finance-related or has broad scope)
  const isFinancialTemplate = ["TCFD", "CUSTOM", "CDP"].some(k =>
    template.code?.toUpperCase().includes(k),
  );
  if (isFinancialTemplate || investments.length > 0 || subsidies.length > 0) {
    checkPageBreak(40);
    y = drawFinanceSection(doc, investments, subsidies, y, W);
  }

  // 5. Selected KPI definitions
  checkPageBreak(40);
  drawSelectedKPIs(doc, allKpiDefinitions, selectedKpiIds, y, W);

  /* ── footers on every page ── */
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    drawFooter(doc, p, totalPages, W, H);
  }

  return doc.output("blob");
}

/* ─── trigger browser download ─── */
export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 200);
}
